- name: "STEP 1 - CONNECT TO F5"
  hosts: "{{ F5_HOST }}"
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - DEPLOY TO F5"
  become: yes
  become_user: root
  become_method: sudo
  hosts: "{{ F5_HOST }}"
  tasks:
    - name: "DEPLOY STACK LIST"
      copy:
        src: "{{ ANSIBLE_PATH }}/{{ item }}"
        dest: "{{ F5_PATH }}/"
        mode: '0755'
        follow: yes
      with_items:
        - "{{ STACK_LOG }}"
