- name: ANSIBLE RUNNING INFOBLOX
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: "TEST"
      debug: msg="{{ ANSIBLE_PATH }}/stack.log"
- name: SEARCH F5 NAT MAPPING LIST
  hosts: 10.241.62.104
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "SEARCH FILE STRING"
      lineinfile:
        path: "{{ ANSIBLE_PATH }}/nat.log"
        line: "10."
        state: present
        
        
        
