- hosts: infoblox
  connection: local
  tasks:
    - name: fetch all networkview objects
      set_fact:
        networkviews: "{{ lookup('nios', 'networkview', provider={'host': 'infoblox', 'username': 'labapi', 'password': 'ansiblelab'}) }}"
