- hosts: webdns.tyc.edu.tw
  connection: local
  tasks:
    - name: fetch all networkview objects
      set_fact:
        #networkviews: "{{ lookup('nios', 'networkview', provider=nios_provider)                                 }}"
        networkviews: "{{ lookup('nios', 'networkview', provider={'host': 'webdns.tyc.edu.tw', 'username': 'ansible', 'password': 'systexansible'}) }}"
    - name: check the networkviews
      debug:
        var: networkviews
    - name: debug specific variable (ipv4 address)
      debug:
        var: networkviews.ipv4addrs[0].ipv4addr
---
- hosts: webdns.tyc.edu.tw
  connection: local
  tasks:
    - name: configure an IPv4 host record
      nios_host_record:
        name: leaf03.ansible.com
        ipv4addrs:
          - ipv4addr:
              "{{ lookup('nios_next_ip', '192.168.100.0/24', provider={'host': 'webdns.tyc.edu.tw', 'username': 'ansible', 'password': 'systexansible'})[0] }}"
        state: present
provider: "{{nios_provider}}"        
        
