- hosts: webdns.tyc.edu.tw
  connection: local
  tasks:
    - name: create network external view
      nios_network:
        network: 163.30.0.0/16
        comment: this is a test comment by Darren
        options:
          - name: domain-name
            value: ansible.com
        state: present
        provider: "{{nios_provider}}"
