- hosts: localhost
  vars:
    nios_provider:
      host: 10.255.4.109
      username: labapi
      password: ansiblelab
  connection: local
  tasks:
    - name: get A record
      set_fact:
        arecord: "{{ lookup('nios', 'record:a', filter={'ipv4addr': '163.30.2.7'}, provider=nios_provider) }}"
    - name: display A record
      debug:
        msg: "{{ arecord }}"
