- hosts: localhost
  connection: local
  vars:
    nios_provider:
      host: webdns.tyc.edu.tw
      username: ansible
      password: systexansible
  tasks:
    - name: fetch all default dns view
      set_fact:
        dns_views: "{{ lookup('nios', filter={'name': 'From_Internet'}, provider=nios_provider) }}"
