- name: "Ansible Test"
  hosts: localhost
  #become: yes
  #become_user: root
  #become_method: sudo
  #connection: local
  tasks:
    - read_csv:
        path: internat_20200206.csv
      delegate_to: localhost

