- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - GET USER INTERNAT IP TO F5"
  hosts: 10.241.62.104
  vars:
    USER_EXT_IP: ""
  tasks:
    - name: "GET USER INTERNAT IP"
      command: "tmsh list ltm nat NAT_{{ USER_IPV4 }}"
      register: nat
    - debug:
        msg: "{{ nat.stdout_lines[4] }}"
      when: nat.stdout_lines | join('') | search('163.30.')
    - debug:
        msg: "{{ nat.stdout_lines[4].split() | join(' ') }}"
#- name: "STEP 3 - UPDATE DNS VIEW"
  #hosts: localhost
  #vars:
  #  nios_provider:
  #    host: "{{ INFOBLOX_HOST }}"
  #    username: "{{ INFOBLOX_USERNAME }}"
  #    password: "{{ INFOBLOX_PASSWORD }}"
  #    wapi_version: "{{ WAPI_VERSION }}"
  #connection: local
  #tasks:
    #- name: INCLUDE VARIABLE BY OTHER YML FILE
    #  include_vars: INFOBLOX_VAR.yml
    #- name: add a comment to an existing A record
      #nios_a_record:
        #view: "{{ INFOBLOX_SCHOOL_VIEW }}"
        #name: "{{ USER_FQDN }}"
        #ipv4: "{{ USER_IPV4 }}"
        #state: present
        #provider: "{{nios_provider}}"
      

