- name: "STEP 1 - CONNECT TO OPENSTACK"
  hosts: overcloud-controller-0
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - DEPLOY TO OPENSTACK"
  hosts: overcloud-controller-0
  vars:
    OPS_PATH: "/home/heat-admin/ansible"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "DEPLOY RESOURCE"
      copy:
        src: stack.sh
        dest: "{{ OPS_PATH }}/stack.sh"
        mode: '0755'
        follow: yes
    - name: "RUN SCRIPT"
      shell: "{{ OPS_PATH }}/stack.sh"
      args:
        chdir: "{{ OPS_PATH }}"
      register: result
    - name: "RESULT"
      debug:
        msg: "{{ result.stdout_lines }}"
    - name: "FETCH RESOURCE"
      fetch:
        src: "{{ OPS_PATH }}/stack.log"
        dest: "{{ ANSIBLE_SCM_PATH }}"
        flat: yes
    - name: "REMOVE RESOURCE"
      file:
        path: "{{ OPS_PATH }}/stack.sh"
        state: absent


