- hosts: webdns.tyc.edu.tw
  connection: local
  tasks:
    - name: fetch all networkview objects
      set_fact:
        networkviews: "{{ lookup('webdns.tyc.edu.tw', 'networkview', provider=nios_provider) }}"
