- name: "STEP 1 - CONNECT TO NODE BY TEST"
  hosts: overcloud-controller-0
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
