- name: "STEP 1 - CONNECT TO OPENSTACK"
  hosts: undercloud
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- hosts: webdns.tyc.edu.tw
  connection: local
  tasks:
    - name: fetch all networkview objects
      set_fact:
        networkviews: "{{ lookup('nios', 'networkview', provider=nios_provider)                                 }}"
        #networkviews: "{{ lookup('nios', 'networkview', provider={'host': 'webdns.tyc.edu.tw', 'username': 'ansible', 'password': 'systexansible'}) }}"
    - name: check the networkviews
      debug:
        var: networkviews

