- name: "Ansible Test"
  hosts: localhost
  become: yes
  become_user: root
  #become_method: sudo
  connection: local
  tasks:
    - read_csv:
        path: "/root/ansible/internat_20200206.csv"
      register: test
