- hosts: webdns.tyc.edu.tw
  connection: local
  tasks:
    - name: configure an IPv4 host record
      nios_host_record:
        name: ns1.ansible.com
        ipv4addrs:
          - ipv4addr:
              "{{ lookup('nios_next_ip', '10.240.0.0/24', provider=nios_provider)[0] }}"
        state: present
provider: "{{nios_provider}}"


