- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"  

- name: Read users from CSV file and return a dictionary
  read_csv:
    path: "/var/lib/awx/projects/_34__auto_network_project/internat_20200206.csv"
  register: users
  delegate_to: localhost
