- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - USE CSV TO CREATE JSON FILE TO F5"
  become: yes
  become_user: root
  become_method: sudo
  hosts: 10.241.62.104
  tasks:
    - name: READ CSV
      read_csv:
        path: "{{ F5_PATH }}/{{ CSV_FILE }}"
        fieldnames: vlan,seg,dnat,dnat_new
        skipinitialspace: yes
        delimiter: ','
      register: csvfile
    - name: CSV RESULT ALL DATA
      debug:
        msg: "{{ csvfile.list }}"
      register: csvfile_list
    - name: SAVING JSON DATA TO FILE
      copy:
        content:  "{{ csvfile_list.msg }}"
        dest: "{{ F5_PATH }}/{{ NAT_LIST_JSON_FILE }}"
- name: "STEP 3 - UPDATE TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "RUN SCRIPT"
      #command: "python {{ F5_PATH }}/nat.py {{ USER_TENANT_NUM }} {{ USER_IPV4 }}" ##### Online Use #####
      command: "python {{ F5_PATH }}/nat.py {{ TENANT_NUM }} {{ USER_IPV4 }}" ##### Demo #####
      args:
        chdir: "{{ F5_PATH }}"
      register: nat_script
    - name: "RESULT"
      debug:
        msg: "{{ nat_script.stdout_lines }}"
        
    ######################################
    #- name: CSV RESULT - SHOW VLAN
    #  debug:
    #    msg: "{{ csvfile.list | map(attribute='vlan') | list }}"
    #  register: csvfile_vlan
    #- name: CSV RESULT - CATCH VLAN 124
    #  debug:
    #    msg: "{{ csvfile_vlan.msg | select('match', '124') | list }}"
    #- name: CSV RESULT TEST 1
    #  debug:
    #    msg: "{{ csvfile_list.msg }}"
    #- name: CSV RESULT TEST 2
    #  debug:
    #    msg: "{{ csvfile_vlan.msg }}"
    #  when: csvfile_vlan.msg  == "124"

    #- name: CSV RESULT TEST 3
    #  debug:
    #    msg: "{{  }}"
    
    #- name: with_sequence
    #  debug:
    #    msg: "{{ item }}"
    #  with_sequence: start=1 end=3 stride=1 #format=testuser%02x
