- name: Infoblox host search play
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
  - name: create host record
    nios_host_record:
      name: host.ansiblezone.com
      view: ansibleDnsView
      ipv4addrs:
        - ipv4addr: "{{ lookup('nios_next_ip', '10.0.0.0/24', provider=nios_provider)[0] }}"
      ipv6addrs:
        - ipv6addr: fd00::2
       ttl: 3600
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
