- hosts: webdns.tyc.edu.tw
  connection: local
  vars:
    nios_provider:
      host: webdns.tyc.edu.tw
      username: ansible
      password: systexansible
  tasks:
    - name: fetch all networkview objects
      set_fact:
        networkviews: "{{ lookup('nios', 'networkview', provider=nios_provider) }}"

    - name: check the networkviews
      debug:
        var: networkviews
