- name: ANSIBLE RUNNING INFOBLOX
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: "TEST"
      debug: msg="{{ ANSIBLE_PATH }}/stack.log"
- name: ANSIBLE SEARCH NAT MAPPING LIST
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: "SEARCH FILE STRING"
      register: presence
      shell: "grep -i '10.' {{ ANSIBLE_PATH }}/nat.log"
    - name: "RESULT"
      debug: msg="presence is changed"
      when: presence is changed
        
