- name: Infoblox host search play
  hosts: localhost
  connection: local
  tasks:
  - name: fetch specific host
    set_fact:
      host: "{{ lookup('nios', 'record:host', filter={'name': 'host1.network.local'}, provider=nios_provider) }}"
  - name: fetch all hosts
    set_fact:
      host: "{{ lookup('nios', 'record:host', provider=nios_provider) }}"
