- hosts: localhost
  vars:
    nios_provider:
      host: 163.30.4.201
      username: ansible
      password: systexansible
  connection: local
  tasks:
    - name: fetch all default dns view
      set_fact:
        dns_views: "{{ lookup('nios', filter={'name': 'From_Internet'}, provider=nios_provider) }}"
