- hosts: localhost
  vars:
    nios_provider:
      host: 10.255.4.109
      username: labapi
      password: ansiblelab
  connection: local
  tasks:
    - name: fetch all default dns view
      set_fact:
        dns_views: "{{ lookup('10.255.4.109', filter={'name': 'From_Internet'}, provider=nios_provider) }}"
