- name: "Ansible Test"
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  connection: local
  tasks:
    - name: sudo su
      shell: sudo su
    - name: cd path
      shell: cd /root/ansible/
    - read_csv:
        path: internat_20200206.csv
      delegate_to: localhost

