- name: Infoblox host search play
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
  - name: fetch specific host
    set_fact:
      host: "{{ lookup('nios', 'ipv4addrs', filter={'host': 'www.whps.tyc.edu.tw'}, provider=nios_provider) }}"
  #- name: fetch all hosts
  #  set_fact:
  #    host: "{{ lookup('nios', 'record:host', provider=nios_provider) }}"
