- hosts: localhost
  vars:
    nios_provider:
      host: 10.255.4.109
      username: labapi
      password: ansiblelab
  connection: local
  tasks:
    - name: get member list
      set_fact:
        arecords: "{{ lookup('nios', 'record:a', provider=nios_provider) }}"
    - name: display all A records
      debug:
        msg: "{{ arecords }}"
