- hosts: localhost
  vars:
    nios_provider:
      host: 10.255.4.109
      username: labapi
      password: ansiblelab
      
  connection: local
  tasks:
    - name: fetch all networkview objects
      set_fact:
        networkviews: "{{ lookup('nios', 'networkview', provider=nios_provider) }}"
