- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - UPDATE DNS VIEW"
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: update the comment for dns test Form_School view
      nios_dns_view:
        name: {new_name: Ansible_School, old_name: ansibleDnsView}
        state: present
        provider: "{{nios_provider}}"
    - name: update the comment for dns test Form_Internat view
      nios_dns_view:
        name: Ansible_Internat
        comment: ansible test Form_Internat view
        state: present
        provider: "{{nios_provider}}"
      

