- name: ANSIBLE RUNNING INFOBLOX
  hosts: localhost
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "SEARCH MAPPING LIST PRIVATE IP"
      shell: "grep -i '10.241' {{ ANSIBLE_PATH }}/nat.log"



