- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - COPY CSV TO ANSIBLE"
  hosts: 10.241.62.104
  #become: yes
  #become_user: root
  #become_method: sudo
  tasks:
    - name: "FETCH RESOURCE"
      fetch:
        src: "{{ F5_PATH }}/{{ CSV_FILE }}"
        dest: "{{ ANSIBLE_PATH }}"
        flat: yes
- name: "ANSIBLE READ CSV"
  hosts: localhost
  tasks:
    - read_csv:
        path: "{{ CSV_FILE }}"
        fieldnames: vlan,seg,dnat,dnat_new
        skipinitialspace: yes
        delimiter: ','
      register: csvfile
      delegate_to: localhost
    - name: CSV RESULT TEST
      debug:
        #msg: "{{ csvfile.list.1.vlan }}"
        msg: "{{ csvfile.list.item }}"
      with_sequence: start=1 end=10
        
    #- name: Loop search 124 Tenant Test
      




