- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
    #- name: Read users from CSV file and return a dictionary
    #  read_csv:
    #    path: "internat_20200206.csv"
    #  register: users
    #- debug:
    #    msg: "{{ users.list.name }}"
    - read_csv:
        path: internat_20200206.csv
      register: test
    - name: Check File Systems for Any changes
      file:
        path: "{{ ANSIBLE_PATH }}"
        owner: awx
        group: awx
        mode: "755"
        state: directory 
        recurse: no 
      loop: "{{ test.list }}"
