- name: ANSIBLE RUNNING INFOBLOX
  hosts: localhost
  
  vars:
    F5_DIR: "/root/A/B/C"
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: "TEST"
      debug: msg="{{ ANSIBLE_PATH }}/stack.log"
    - name: "SEARCH FILE STRING"
      register: presence
      shell: "grep -i '10.241' {{ ANSIBLE_PATH }}/nat.log"
    - name: Creates directory
      file:
        path: "{{ F5_DIR }}"
        state: directory
        owner: root
        group: root
        mode: 0775
        recurse: yes
#- name: ANSIBLE SEARCH NAT MAPPING LIST
#  hosts: localhost 
#  tasks:
#    - name: "SEARCH FILE STRING"
#      register: presence
#      shell: "grep -i '10.241' {{ ANSIBLE_PATH }}/nat.log"


