- hosts: 10.255.4.109
  connection: local
  tasks:
    - name: fetch all networkview objects
      set_fact:
        networkviews: "{{ lookup('nios', 'networkview', provider={'host': '10.255.4.109', 'username': 'labapi', 'password': 'ansiblelab'}) }}"
