- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - UPDATE DNS VIEW"
  hosts: localhost
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: update the comment for dns view
      nios_dns_view:
        name: ansible_school
        comment: ansible test Form_School view
        state: present
    - name: update the comment for dns view
      nios_dns_view:
        name: ansible_internat
        comment: ansible test Form_Internat view
        state: present


