- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "Ansible Test"
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  connection: local
  tasks:
    - read_csv:
        path: "{{ ANSIBLE_PATH }}/internat_20200206.csv"
      register: test
    - name: Check File Systems for Any changes
      file:
        path: "{{ ANSIBLE_PATH }}/internat_20200206.csv"
        owner: awx
        group: awx
        mode: "755"
      loop: "{{ test.list }}"
