- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - GET USER INTERNAT IP TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "RUN SCRIPT"
      command: "python {{ F5_PATH }}dns.py {{ USER_IPV4 }}"
      args:
        chdir: "{{ F5_PATH }}"
      register: dns_script
    - name: "RESULT"
      debug:
        msg: "{{ dns_script.stdout_lines }}"
- name: "STEP 3 - UPDATE DNS VIEW"
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: "RUN SCRIPT"
      command: "python2 {{ ANSIBLE_PATH }}dns_sftp.py {{ F5_HOST }} {{ F5_USERNAME }} {{ F5_PASSWORD }} {{ F5_PATH }} {{ USER_IPV4 }}"
      args:
        chdir: "{{ ANSIBLE_PATH }}"
      register: USER_INTERNAT_IP
    - name: "RESULT"
      debug:
        msg: "{{ USER_INTERNAT_IP.stdout }}"
    - name: INCLUDE VARIABLE BY OTHER YML FILE
      include_vars: INFOBLOX_VAR.yml
    - name: "DNS MODE"
      debug:
        msg: "{{ DNS_MODE }}"
      register: is_dns_mode
    - name: WHEN CREATE MODE - ADD A RECORD
      nios_a_record:
        view: "{{ INFOBLOX_SCHOOL_VIEW }}"
        name: "{{ USER_FQDN }}"
        ipv4: "{{ USER_IPV4 }}"
        state: present
        provider: "{{nios_provider}}"
      nios_a_record:
        view: "{{ INFOBLOX_INTERNAT_VIEW }}"
        name: "{{ USER_FQDN }}"
        ipv4: "{{ USER_INTERNAT_IP.stdout }}"
        state: present
        provider: "{{nios_provider}}"
      when: is_dns_mode.msg == "add"
    - name: "MODE IS DELETE"
      debug:
        msg: "mode is del"
      when: is_dns_mode.msg == "del"
    - name: "MODE IS SHOW"
      debug:
        msg: "mode is show"
      when: is_dns_mode.msg == "show"
- name: "STEP 4 - REMOVE TMP FILE"
  hosts: 10.241.62.104
  tasks:
    - name: "REMOVE FILE"
      file:
        path: "{{ F5_PATH }}dns_{{ USER_IPV4 }}.log"
        state: absent

      

