- hosts: localhost
  vars:
    nios_provider:
      host: 10.255.4.109
      username: labapi
      password: ansiblelab

  connection: local
  tasks:
   - name: create DNS view
     nios_dns_view:
       name: ansibleDnsView
       network_view: ansibleNetView
       extattrs:
         Site: Test Site
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
