- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"  
- name: "STEP 2 - DEPLOY TO F5"
  hosts: 10.241.62.104
  var:
    DEST_DIR: "/config/ansible"
    DEPLOY_FILE1: "stack.log"
    DEPLOY_FILE2: "nat.log"
    DEPLOY_FILE3: "nat.sh"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "DEPLOY RESOURCE1"
      copy:
        src: "{{ ANSIBLE_PATH }}/stack.log"
        dest: "{{ DEST_DIR }}"
        mode: '0755'
        follow: yes

    #- name: "DEPLOY RESOURCE2"
    #  copy:
    #    src: "{{ ANSIBLE_PATH }}/nat.log"
    #    dest: /config/ansible/
    #    mode: '0644'
    #    follow: yes
    #- name: "DEPLOY RESOURCE3"
    #  copy:
    #    src: "{{ ANSIBLE_PATH }}/nat.sh"
    #    dest: /config/ansible/
    #    mode: '0755'
    #    follow: yes
#- name: "STEP 3 - UPDATE TO F5"
#  hosts: 10.241.62.104
#  become: yes
#  become_user: root
#  become_method: sudo
#  tasks:
#    - name: "RUN SCRIPT"
#      shell: "{{ F5_DIR }}/nat.sh"
#      args:
#        chdir: /config/ansible/
#      register: nat
#    - name: "RESULT"
#      debug:
#        msg: "{{ nat.stdout_lines }}"
        
        
