- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - COPY CSV TO ANSIBLE"
  hosts: 10.241.62.104
  tasks:
    - name: "FETCH RESOURCE"
      fetch:
        src: "{{ F5_PATH }}/{{ CSV_FILE }}"
        dest: "{{ ANSIBLE_PATH }}"
        flat: yes
- name: "ANSIBLE READ CSV"
  hosts: localhost
  tasks:
    - read_csv:
        path: "{{ CSV_FILE }}"
        fieldnames: vlan,seg,dnat,dnat_new
        skipinitialspace: yes
        delimiter: ','
      register: csvfile
      delegate_to: localhost
    - name: CSV RESULT TEST
      debug:
        msg: "{{ csvfile.list }}{{ item }}"
      loop:
        - ".1.vlan"
        - ".2.vlan"
      
          
    #- name: CSV RESULT csvfile_vlan array 1
    #  debug:
    #    msg: "{{ csvfile.list.1.vlan }}"
    #- name: with_sequence
    #  debug:
    #    msg: "{{ item }}"
    #  with_sequence: start=1 end=3 stride=1 #format=testuser%02x
