- hosts: webdns.tyc.edu.tw
  connection: local
  tasks:
    - name: create network external view
      nios_network:
        network: 163.30.0.0/16
        comment: this is a test comment by Darren
        options:
          - name: domain-name
            value: ansible.com
        state: present
        provider: "{{nios_provider}}"
- hosts: webdns.tyc.edu.tw
  connection: local
  tasks:
    - name: configure an IPv4 host record
      nios_host_record:
        name: ns1.ansible.com
        ipv4addrs:
          - ipv4addr:
              "{{ lookup('nios_next_ip', '163.30.0.0/16', provider=nios_provider)[0] }}"
        state: present
        provider: "{{nios_provider}}"

