- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - COPY CSV TO ANSIBLE"
  hosts: 10.241.62.104
  tasks:
    - name: "FETCH RESOURCE"
      fetch:
        src: "{{ F5_PATH }}/{{ CSV_FILE }}"
        dest: "{{ ANSIBLE_PATH }}"
        flat: yes
- name: "ANSIBLE READ CSV"
  hosts: localhost
  tasks:
    - name: READ CSV
      read_csv:
        path: "{{ CSV_FILE }}"
        fieldnames: vlan,seg,dnat,dnat_new
        skipinitialspace: yes
        delimiter: ','
      register: csvfile
      delegate_to: localhost
    #- name: CSV RESULT ALL DATA 
    #  debug:
    #    msg: "{{ csvfile.list }}"
    #  register: csvfile_list
    - name: CSV RESULT - SHOW VLAN
      debug:
        msg: "{{ csvfile.list | map(attribute='vlan') | list }}"
      register: csvfile_vlan
    - name: CSV RESULT - CATCH VLAN 124
      debug:
        #msg: "{{ csvfile_vlan.msg | select('match', '124') | list }}"
        msg: "{{ csvfile_vlan.msg | select('match', '{{ item }}') | list }}"
        #register: letsencrypt_challenge
      with_items: "{{ TENANT_NUM }}"
    #- name: CSV RESULT TEST 1
    #  debug:
    #    msg: "{{ csvfile_list.msg }}"
    #- name: CSV RESULT TEST 2
    #  debug:
    #    msg: "{{ csvfile_vlan.msg }}"
    #  when: csvfile_vlan.msg  == "124"

    #- name: CSV RESULT TEST 3
    #  debug:
    #    msg: "{{  }}"
    
    #- name: with_sequence
    #  debug:
    #    msg: "{{ item }}"
    #  with_sequence: start=1 end=3 stride=1 #format=testuser%02x
